config_map:     
  - name: PRODUCT
    value: "{{ product.name }}"    
  - name: JAEGER_SERVICE_NAME
    value: "{{ project }}-console-environment-api"
  - name: JAEGER_SAMPLER_TYPE
    value: const
  - name: JAEGER_SAMPLER_PARAM
    value: 1
  - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
    value: "jaeger-agent.{{ product.name }}-monitoring.svc:5778"    
  - name: JAEGER_AGENT_HOST
    value: "jaeger-agent.{{ product.name }}-monitoring.svc"  
  - name: ENVIRONMENT_API_SERVICE_URI
    value: "http://console-environment-api.{{ project }}.svc:8080"          
  - name: FEATURE_API_SERVICE_URI
    value: "http://console-feature-api.{{ project }}.svc:8080"
  - name: JENKINS_API_SERVICE_URI
    value: "http://console-jenkins-api.{{ project }}.svc:8080"
  - name: USER_API_SERVICE_URI
    value: "http://console-user-api.{{ project }}.svc:8080"
  - name: PROJECT_API_SERVICE_URI
    value: "http://console-project-api.{{ project }}.svc:8080"
  - name: TRELLO_API_SERVICE_URI
    value: "http://console-project-api.{{ project }}.svc:8080"    
    
      