config_map:     
  - name: JAEGER_SERVICE_NAME
    value: "{{ project }}-{{ microservice.name }}"
  - name: JAEGER_SAMPLER_TYPE
    value: const
  - name: JAEGER_SAMPLER_PARAM
    value: 1
  - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
    value: "jaeger-agent.{{ project }}.svc:5778"    
  - name: JAEGER_AGENT_HOST
    value: "jaeger-agent.{{ project }}.svc"  
  - name: ENVIRONMENT_API_SERVICE_URI
    value: "http://environment-api.{{ project }}.svc:8080"          
  - name: FEATURE_API_SERVICE_URI
    value: "http://feature-api.{{ project }}.svc:8080"
  - name: JENKINS_API_SERVICE_URI
    value: "http://jenkins-api.{{ project }}.svc:8080"
  - name: USER_API_SERVICE_URI
    value: "http://user-api.{{ project }}.svc:8080"
  - name: PROJECT_API_SERVICE_URI
    value: "http://project-api.{{ project }}.svc:8080"
  - name: TRELLO_API_SERVICE_URI
    value: "http://project-api.{{ project }}.svc:8080"    
    
      